# This is a basic workflow to help you get started with Actions

name: Start BADNAM`BOT

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      bot_token:
          description: '7276555883:AAECVqvWzsLJvWQHC-LgjDK-h_Y-l_b4UHQ' #यहां पर अपना बोट टोकन डाले।
          required: true
env:
  TZ: America/New_York
  BOT_TOKEN: ${{ github.event.inputs.bot_token }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: starting bot
        run: |
          pip install telebot timedelta
          sudo apt install python3 -y
          sudo apt-get install -y
          chmod +x main.py
          pip install telebot 
          python main.py ${BOT_TOKEN} &

      - name: Keep the bot active
        run: sleep $((14 * 24 * 60 * 60))


      
